/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Codigo.Control_Musica_Web;
import Codigo.Metodos_Compras;
import Codigo.Metodos_Para_Ventanas;
import Codigo.Modelo_Tabla;
import Codigo_Archivos.CRUB_Archivos;
import Objetos.Catalogo_Musica;
import Objetos.Catalogo_Peliculas;
import Objetos.Dato_Compras;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class Ventana_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Usuario
     */
    String[] usuario;
    public static ArrayList<Dato_Compras> discos_para_comprar = new ArrayList();
    ArrayList<Catalogo_Musica> discos_musica = new ArrayList<>();
    ArrayList<Catalogo_Peliculas> discos_pelicula = new ArrayList<>();
    Control_Musica_Web control = new Control_Musica_Web();
    Modelo_Tabla tabla = new Modelo_Tabla();

    public Ventana_Usuario(String[] usuario) {
        initComponents();
        Actualizar_Tabla();
        txtBuscador1.setEnabled(false);
        this.usuario = usuario;
        CRUB_Archivos crub_archivos = new CRUB_Archivos();
        discos_pelicula = crub_archivos.Buscar_Informacion_Peliculas_Archi();
        discos_musica = crub_archivos.Buscar_Informacion_Musica_Archi();
        Colocar_Precio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMusica = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla_Musica = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_Peliculas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Compras = new javax.swing.JTable();
        lblCosto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtBuscador = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        txtBuscador1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        PanelMusica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla_Musica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_Musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_MusicaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla_Musica);

        javax.swing.GroupLayout PanelMusicaLayout = new javax.swing.GroupLayout(PanelMusica);
        PanelMusica.setLayout(PanelMusicaLayout);
        PanelMusicaLayout.setHorizontalGroup(
            PanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        PanelMusicaLayout.setVerticalGroup(
            PanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla_Peliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_Peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PeliculasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Tabla_Peliculas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla_Compras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabla_Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ComprasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla_Compras);

        lblCosto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCosto.setText("Total a pagar: ₡");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jButton1.setText("Comprar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblCosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Buscar:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Disco", "Autor", "Categoria", "Cancion", "Precio" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        txtBuscador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setText("Parar Cancion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtBuscador1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBuscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscador1KeyReleased(evt);
            }
        });

        jMenu1.setText("Cerrar Sesion");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscador)
                            .addComponent(txtBuscador1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void Tabla_MusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_MusicaMouseClicked
        Metodos_Para_Ventanas mpv = new Metodos_Para_Ventanas();
        Modelo_Tabla mt = new Modelo_Tabla();
        int columna = Tabla_Musica.getColumnModel().getColumnIndexAtX(evt.getX());
        int cantidad = 1;
        int fila = evt.getY() / Tabla_Musica.getRowHeight();
        if (fila < Tabla_Musica.getRowCount() && fila >= 0 && columna < Tabla_Musica.getColumnCount() && columna >= 0) {
            Object value = Tabla_Musica.getValueAt(fila, columna);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("agregar")) {
                    String disco = mt.Obtener_Disco(Tabla_Musica, Tabla_Musica.getSelectedRow());
                    try {
                        cantidad = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese la cantidad deseada: "));
                        int posicion = mpv.Buscar_Objeto_Musica(discos_musica, disco);
                        DefaultTableModel modelo = mt.Actualizar_Tabla_Compras_Musica(Tabla_Compras, (Catalogo_Musica) discos_musica.get(posicion), usuario, cantidad);
                        Tabla_Compras.setModel(modelo);
                    } catch (NumberFormatException ex) {
                        System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "No ingresastes un numero");
                    }
                    Colocar_Precio();
                } else {
                    control.Play(boton.getName());
                }
            }
        }
    }//GEN-LAST:event_Tabla_MusicaMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void Tabla_PeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PeliculasMouseClicked
        Metodos_Para_Ventanas mpv = new Metodos_Para_Ventanas();
        Modelo_Tabla mt = new Modelo_Tabla();
        int columna = Tabla_Peliculas.getColumnModel().getColumnIndexAtX(evt.getX());
        int cantidad = 1;
        int fila = evt.getY() / Tabla_Peliculas.getRowHeight();
        if (fila < Tabla_Peliculas.getRowCount() && fila >= 0 && columna < Tabla_Peliculas.getColumnCount() && columna >= 0) {
            Object value = Tabla_Peliculas.getValueAt(fila, columna);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("agregar")) {
                    String disco = mt.Obtener_Disco(Tabla_Peliculas, Tabla_Peliculas.getSelectedRow());
                    try {
                        cantidad = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese la cantidad deseada: "));
                        int posicion = mpv.Buscar_Objeto_Pelicula(discos_pelicula, disco);
                        DefaultTableModel modelo = mt.Actualizar_Tabla_Compras_Peliculas(Tabla_Compras, (Catalogo_Peliculas) discos_pelicula.get(posicion), usuario, cantidad);
                        Tabla_Compras.setModel(modelo);
                    } catch (NumberFormatException ex) {
                        System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "No ingresastes un numero");
                    }
                    Colocar_Precio();
                } else {
                    control.Ver_Trailer(boton.getName());
                }

            }
        }
    }//GEN-LAST:event_Tabla_PeliculasMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        control.Stop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Tabla_ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ComprasMouseClicked
        Modelo_Tabla mt = new Modelo_Tabla();
        String disco = mt.Obtener_Disco(Tabla_Compras, Tabla_Compras.getSelectedRow());
        int result = JOptionPane.showConfirmDialog(null,
                "¿Quieres eliminar " + disco + " de tu lista compras?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            DefaultTableModel modelo = (DefaultTableModel) Tabla_Compras.getModel();
            modelo.removeRow(Tabla_Compras.getSelectedRow());
            DefaultTableModel modelo_nuevo = mt.Eliminar_Objeto_Compra(disco, Tabla_Compras);
            Tabla_Compras.setModel(modelo_nuevo);
            Colocar_Precio();
        }

    }//GEN-LAST:event_Tabla_ComprasMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("Precio")) {
            txtBuscador1.setEnabled(true);
            txtBuscador.setText("");
        } else {
            txtBuscador1.setEnabled(false);
            txtBuscador1.setText("");
            txtBuscador.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        if (jComboBox1.getSelectedItem().equals("Precio")) {
            char caracter = evt.getKeyChar();
            if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            }
        }
        Actualizar_Tabla();
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void txtBuscador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscador1KeyReleased
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        Actualizar_Tabla();
    }//GEN-LAST:event_txtBuscador1KeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Metodos_Compras mc = new Metodos_Compras();
        boolean compras_realizadas = mc.Realizando_Compras_Peliculas_Musica(discos_pelicula, discos_musica);
        if (compras_realizadas) {
            JOptionPane.showMessageDialog(null, "Gracias por su compra");
            CRUB_Archivos crub_archivos = new CRUB_Archivos();
            discos_pelicula = crub_archivos.Buscar_Informacion_Peliculas_Archi();
            discos_musica = crub_archivos.Buscar_Informacion_Musica_Archi();
            discos_para_comprar.clear();
            Modelo_Tabla mt = new Modelo_Tabla();
            mt.Modelo_Tabla_Musica(Tabla_Musica, "", "0", "0");
            mt.Modelo_Tabla_Pelicula(Tabla_Peliculas, "", "0", "0");
            DefaultTableModel modelo = mt.Limpiar_Tabla(Tabla_Compras);
            Tabla_Compras.setModel(modelo);
            Colocar_Precio();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Colocar_Precio();
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMusica;
    private javax.swing.JTable Tabla_Compras;
    private javax.swing.JTable Tabla_Musica;
    private javax.swing.JTable Tabla_Peliculas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtBuscador1;
    // End of variables declaration//GEN-END:variables

    private void Actualizar_Tabla() {
        tabla.Modelo_Tabla_Pelicula(Tabla_Peliculas, (String) jComboBox1.getSelectedItem(), txtBuscador.getText(), txtBuscador1.getText());
        tabla.Modelo_Tabla_Musica(Tabla_Musica, (String) jComboBox1.getSelectedItem(), txtBuscador.getText(), txtBuscador1.getText());
    }

    private void Colocar_Precio() {
        Metodos_Compras mt = new Metodos_Compras();
        int costo = mt.Costo_Total(discos_para_comprar);
        lblTotal.setText(String.valueOf(costo));
    }
}
